### ISSUE TITLE
The line '#!/bin/bash' is faulting in the linux script

### ISSUE THREAD

**Issue by mapaiva** [nospaceships/node-os-service#7] opened 2015-10-06 18:51 UTC
The line `'#!/bin/bash'` that make the script executable as a service is faulting in the index.js file.

**Comment by stephenwvickers** [comment] 2015-10-07 16:53
Hi,

Can I confirm that you issue is that a shebang line does not exist in the start/stop script generated by this module?

Thanks

Steve

**Comment by mapaiva** [comment] 2015-10-07 18:14
That was the generated script

``` bash
### BEGIN INIT INFO
# Provides:          node-afx-rdi-plugin
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start node-afx-rdi-plugin at boot time
# Description:       Enable node-afx-rdi-plugin service.
### END INIT INFO

# chkconfig:   2345 99 1
# description: node-afx-rdi-plugin

set_pid () {
    unset PID
    _PID=`head -1 "/home/matheus/Codit/node-afx-rdi-plugin/lib/service.js.pid" 2>/dev/null`
    if [ $_PID ]; then
        kill -0 $_PID 2>/dev/null && PID=$_PID
    fi
}

force_reload () {
    stop
    start
}

restart () {
    stop
    start
}

start () {
    CNT=5

    set_pid

    if [ -z "$PID" ]; then
        echo starting node-afx-rdi-plugin

        "/usr/bin/nodejs"  "/home/matheus/Codit/node-afx-rdi-plugin/lib/service.js"  >/dev/null 2>&1 &

        echo $! > "/home/matheus/Codit/node-afx-rdi-plugin/lib/service.js.pid"

        while [ : ]; do
            set_pid

            if [ -n "$PID" ]; then
                echo started node-afx-rdi-plugin
                break
            else
                if [ $CNT -gt 0 ]; then
                    sleep 1
                    CNT=`expr $CNT - 1`
                else
                    echo ERROR - failed to start node-afx-rdi-plugin
                    break
                fi
            fi
        done
    else
        echo node-afx-rdi-plugin is already started
    fi
}

status () {
    set_pid

    if [ -z "$PID" ]; then
        exit 1
    else
        exit 0
    fi
}

stop () {
    CNT=5

    set_pid

    if [ -n "$PID" ]; then
        echo stopping node-afx-rdi-plugin

        kill $PID

        while [ : ]; do
            set_pid

            if [ -z "$PID" ]; then
                rm "/home/matheus/Codit/node-afx-rdi-plugin/lib/service.js.pid"
                echo stopped node-afx-rdi-plugin
                break
            else
                if [ $CNT -gt 0 ]; then
                    sleep 1
                    CNT=`expr $CNT - 1`
                else
                    echo ERROR - failed to stop node-afx-rdi-plugin
                    break
                fi
            fi
        done
    else
        echo node-afx-rdi-plugin is already stopped
    fi
}

case $1 in
    force-reload)
        force_reload
        ;;
    restart)
        restart
        ;;
    start)
        start
        ;;
    status)
        status
        ;;
    stop)
        stop
        ;;
    *)
        echo "usage: $0 <force-reload|restart|start|status|stop>"
        exit 1
        ;;
esac
```

I've just add the `#!/bin/bash` at the first line and it works.

**Comment by stephenwvickers** [comment] 2015-10-09 19:02
Duplicate of #4

**Closed as completed by stephenwvickers** 2015-10-09 19:02 UTC
